import type {Metadata} from 'next';

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';

import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Toaster} from '@/components/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-testid="app-root">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header
            data-testid="app-header"
            className="flex justify-end items-center p-4 gap-4 h-16"
          >
            <SignedOut>
              <div data-testid="auth-signed-out-container">
                <SignInButton data-testid="auth-sign-in-button" />
                <SignUpButton data-testid="auth-sign-up-trigger">
                  <button
                    data-testid="auth-sign-up-button"
                    className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer"
                  >
                    Sign Up
                  </button>
                </SignUpButton>
              </div>
            </SignedOut>
            <SignedIn>
              <div data-testid="auth-signed-in-container">
                <UserButton data-testid="auth-user-button" />
              </div>
            </SignedIn>
          </header>
          <main data-testid="app-main-content">{children}</main>
          <Toaster data-testid="app-toaster" />
        </body>
      </html>
    </ClerkProvider>
  );
}
